// <auto-generated />
namespace LexiconLMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_Parent_IDs_To_Moduel_and_Activity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_Parent_IDs_To_Moduel_and_Activity));
        
        string IMigrationMetadata.Id
        {
            get { return "201607121325254_Added_Parent_IDs_To_Moduel_and_Activity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
